### ISSUE TITLE
node backend/server.js  problem

### ISSUE THREAD

**Issue by samatzhusup** [Prince-Shivaram/BookStore-App#2]
[nodemon] starting `node backend/server.js`
[0] /home/samat/WebstormProjects/Didgo-1/BookStore-App/backend/server.js:1
[0] import path from 'path'
[0]        ^^^^
[0] 
[0] SyntaxError: Unexpected identifier
[0]     at Module._compile (internal/modules/cjs/loader.js:723:23)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[0]     at Module.load (internal/modules/cjs/loader.js:653:32)
[0]     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[0]     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
[0]     at startup (internal/bootstrap/node.js:283:19)
[0]     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
[0] [nodemon] app crashed - waiting for file changes before starting...

.env file
NODE_ENV = development
PORT = 5000
MONGO_URI = 'mongodb://127.0.0.1:27014/Bookstroreapp'
JWT_SECRET = 'a489407ef4e324f69ed083b80d2daab72ade457ca6d8a1c8110af78b608ba66f'
PAYPAL_CLIENT_ID = a489407ef4e324f69ed083b80d2daab72ade457ca6d8a1c8110af78b608ba66f

Node version!
v10.19.0

**Comment by samatzhusup** [comment]
I was solving with nodejs update
